### PR TITLE
Display comments

### PR DESCRIPTION
**Pull request by Bifabig**
- Add comment form
- Display comments for each card

### CODE REVIEW

**Comment by MarcoDiaz2000** [comment]
**Hi @Bifabig** 👏

While you made a great effort in this project, but there is an issue to be resolved.

so close

### **Required Changes ♻️**

- [ ] When you add a comment the system displays an error.

error when submit comment

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

**Review by MarcoDiaz2000 — CHANGES_REQUESTED** [review]
**Hi @Bifabig** 👏

While you made a great effort in this project, but there is an issue to be resolved.

so close

### **Required Changes ♻️**

- [x] When you add a comment the system displays an error.

error when submit comment

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @MarcoDiaz2000 

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

**Comment by Bifabig** [comment]
> **Hi @Bifabig** 👏
> 
> While you made a great effort in this project, but there is an issue to be resolved.
> 
> so close
> 
> ### **Required Changes ♻️**
> * [ ]  When you add a comment the system displays an error.
> 
> error when submit comment
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification @MarcoDiaz2000
> 
> Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

Hi @MarcoDiaz2000, Kindly review it again...

**Review by MarcoDiaz2000 — APPROVED** [review]
Hi @Bifabig  👋👋, 

StandingOvationGIF (2)


Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights✅✅

- [x] Add comment form👍.
- [x] Display comments for each card👍.

## Optional suggestions
_No optional suggestion, keep going👍_

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**Pull request merged**
