### PR TITLE
Display number of likes and add new likes

### PR DESCRIPTION
**Pull request by MarcoDiaz2000**
- Display the number of likes for each item on the Homepage
- Create function: add a new like through API

### CODE REVIEW

**Review by Bifabig — CHANGES_REQUESTED** [review]
Hi @MarcoDiaz2000 

Great job so far 👍 

I would suggest that you make the like button only increase the counter by one, because when I tried clicking on the button multiple times. The counter increased multiple times as well before the like button changed to clicked.

**Comment by MarcoDiaz2000** [comment]
> Hi @MarcoDiaz2000
> 
> Great job so far 👍
> 
> I would suggest that you make the like button only increase the counter by one, because when I tried clicking on the button multiple times. The counter increased multiple times as well before the like button changed to clicked.

Okay, I will make the suggested changes.
Thank you

**Comment by MarcoDiaz2000** [comment]
> > Hi @MarcoDiaz2000
> > Great job so far 👍
> > I would suggest that you make the like button only increase the counter by one, because when I tried clicking on the button multiple times. The counter increased multiple times as well before the like button changed to clicked.
> 
> Okay, I will make the suggested changes. Thank you

Hi, @Bifabig The changes are done, could you help me by checking them?
Thanks

**Review by Bifabig — APPROVED** [review]
# Approved 🟢
Hi @MarcoDiaz2000, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


## Highlights
- Like button works 🥇 
- Code is clean and well organized 🧼 💯 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@Bifabig) in your question so I can receive the notification.

**Pull request merged**
